# Crystal Yacc Parser Template
# Generated by Lrama for Crystal

<%- if output.aux[:crystal_header] -%>
<%= output.aux[:crystal_header] %>
<%- end -%>

module Yacc
  <%- if output.aux.prologue -%>
  # User prologue code
  <%= output.aux.prologue %>
  <%- end -%>

  # Parser value type
  struct YYSTYPE
    property val : Int32

    def initialize
      @val = 0
    end
  end

  # Parser location type
  struct YYLTYPE
    property first_line : Int32
    property first_column : Int32
    property last_line : Int32
    property last_column : Int32

    def initialize
      @first_line = 0
      @first_column = 0
      @last_line = 0
      @last_column = 0
    end
  end

  # Parser configuration constants
  YYBISON = 30802
  YYBISON_VERSION = "3.8.2"
  YYSKELETON_NAME = "yacc.cr"

  # Default stack depth
  YYINITDEPTH = 200
  YYMAXDEPTH = 10000

  # Special tokens
  YYEMPTY = -2
  YYEOF = 0
  YYTERROR = 1
  YYUNDEF = 2

  # Parser table constants
  YYFINAL = <%= output.yyfinal %>
  YYLAST = <%= output.yylast %>
  YYNTOKENS = <%= output.yyntokens %>
  YYNNTS = <%= output.yynnts %>
  YYNRULES = <%= output.yynrules %>
  YYNSTATES = <%= output.yynstates %>
  YYMAXUTOK = <%= output.yymaxutok %>

  # Parser tables
  YYTRANSLATE = [
    <%= output.yytranslate %>
  ]

  YYPACT = [
    <%= output.int_array_to_string(output.context.yypact) %>
  ]

  YYDEFACT = [
    <%= output.int_array_to_string(output.context.yydefact) %>
  ]

  YYPGOTO = [
    <%= output.int_array_to_string(output.context.yypgoto) %>
  ]

  YYDEFGOTO = [
    <%= output.int_array_to_string(output.context.yydefgoto) %>
  ]

  YYTABLE = [
    <%= output.int_array_to_string(output.context.yytable) %>
  ]

  YYCHECK = [
    <%= output.int_array_to_string(output.context.yycheck) %>
  ]

  YYSTOS = [
    <%= output.int_array_to_string(output.context.yystos) %>
  ]

  YYR1 = [
    <%= output.int_array_to_string(output.context.yyr1) %>
  ]

  YYR2 = [
    <%= output.int_array_to_string(output.context.yyr2) %>
  ]

  # Parser state
  class Parser
    property yychar : Int32 = YYEMPTY
    property yylval : YYSTYPE
    property yylloc : YYLTYPE

    # Stack pointers and stacks
    property yyssp : Int32 = 0
    property yyvsp : Int32 = 0
    property yylsp : Int32 = 0
    property yyss : Array(Int32)
    property yyvs : Array(YYSTYPE)
    property yyls : Array(YYLTYPE)
    property yystacksize : Int32 = YYINITDEPTH

    def initialize
      @yylval = YYSTYPE.new
      @yylloc = YYLTYPE.new
      @yyss = Array(Int32).new(YYINITDEPTH, 0)
      @yyvs = Array(YYSTYPE).new(YYINITDEPTH, YYSTYPE.new)
      @yyls = Array(YYLTYPE).new(YYINITDEPTH, YYLTYPE.new)
    end

    def yyparse
      yystate = 0
      yyn = 0
      yylen = 0
      yyresult = 0
      yynerrs = 0
      yyerrstatus = 0

      # Initialize stack pointers
      yyssp = 0
      yyvsp = 0
      yylsp = 0

      # Push initial state
      yyss[yyssp] = yystate

      loop do
        # Look up action for current state
        yyn = YYPACT[yystate]
        if yypact_value_is_default(yyn)
          # Default action
          yyn = YYDEFACT[yystate]
          if yyn == 0
            # Syntax error
            yyerror("syntax error")
            yynerrs += 1
            yyerrstatus = 3
            # Error recovery
            if yychar == YYEOF
              return 1
            end
            yychar = YYEMPTY
            next
          end
        else
          # Not default action, need lookahead
          if yychar == YYEMPTY
            yychar = yylex
            if yychar < 0
              yychar = YYEOF
            end
          end
          yyn += yychar
          if yyn < 0 || yyn > YYLAST || YYCHECK[yyn] != yychar
            yyn = YYDEFACT[yystate]
          else
            yyn = YYTABLE[yyn]
            if yyn <= 0
              if yytable_value_is_error(yyn)
                # Syntax error
                yyerror("syntax error")
                yynerrs += 1
                yyerrstatus = 3
                # Error recovery
                if yychar == YYEOF
                  return 1
                end
                yychar = YYEMPTY
                next
              end
              yyn = -yyn
            end
          end
        end

        # Reduce or shift
        if yyn > 0
          # Shift
          yystate = yyn
          yyss[yyssp + 1] = yystate
          yyvs[yvsp + 1] = yylval
          yyls[yylsp + 1] = yylloc
          yyssp += 1
          yyvsp += 1
          yylsp += 1
          yychar = YYEMPTY
        else
          # Reduce
          yyn = -yyn
          yylen = yyr2[yyn]
          # Perform semantic action
          yyval = yyvs[yvsp - yylen + 1]
          yyloc = yyls[yylsp - yylen + 1]
          case yyn
          <%= output.user_actions %>
          end
          # Pop stack
          yyssp -= yylen
          yyvsp -= yylen
          yylsp -= yylen
          # Push result
          yyvsp += 1
          yyvs[yvsp] = yyval
          yylsp += 1
          yyls[yylsp] = yyloc
          # Look up next state
          yyn = yyr1[yyn]
          yystate = yypgoto[yyn - YYNTOKENS] + yyss[yyssp]
          if yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == yyss[yyssp]
            yystate = yytable[yystate]
          else
            yystate = yydefgoto[yyn - YYNTOKENS]
          end
          yyss[yyssp + 1] = yystate
          yyssp += 1
        end

        if yystate == YYFINAL
          return 0
        end
      end
    end

    # Token translation method
    def yytranslate(token : Int32) : Int32
      if 0 <= token <= YYMAXUTOK
        YYTRANSLATE[token]
      else
        YYUNDEF
      end
    end

    # Error reporting method
    def yyerror(message : String)
      STDERR.puts "Syntax error: #{message}"
    end

    # Table value checks
    def yypact_value_is_default(value : Int32) : Bool
      value == YYPACT_NINF
    end

    def yytable_value_is_error(value : Int32) : Bool
      value == YYTABLE_NINF
    end

    <%- if output.aux[:crystal_inner] -%>
    <%= output.aux[:crystal_inner] %>
    <%- end -%>

    # These should be defined by the user or generated code
    def yylex : Int32
      # User must implement this method
      raise "yylex not implemented"
    end

    # Default values for table constants
    private YYPACT_NINF = -1000
    private YYTABLE_NINF = -1000

  end
end
    <%- if output.aux.epilogue -%>
    <%= output.aux.epilogue %>
    <%- end -%>
<%- if output.aux[:crystal_footer] -%>
<%= output.aux[:crystal_footer] %>
<%- end -%>
